<?php

use App\Http\Controllers\AutoconfigController;
use App\Http\Controllers\AutoDiscoverController;
use App\Http\Controllers\ImpersonationController;
use App\Http\Controllers\LanguageController;
use App\Models\MysqlCredential;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect('/jabali-panel');
});

// phpMyAdmin SSO — generates a one-time token and redirects to the signon script on nginx (port 443)
Route::get('/phpmyadmin-sso', function (\Illuminate\Http\Request $request) {
    $database = $request->query('database', '');
    $user = $request->user();
    $username = $user->username;
    $adminUsername = $username.'_admin';

    $credential = MysqlCredential::where('user_id', $user->id)
        ->where('mysql_username', $adminUsername)
        ->first();

    if (! $credential) {
        $credential = MysqlCredential::where('user_id', $user->id)->first();
    }

    if (! $credential) {
        abort(404, 'No database credentials found.');
    }

    $token = bin2hex(random_bytes(32));
    Cache::put('phpmyadmin_token_'.$token, [
        'username' => $credential->mysql_username,
        'password' => Crypt::decryptString($credential->mysql_password_encrypted),
        'database' => $database,
    ], now()->addMinutes(5));

    $scheme = $request->getScheme();
    $host = $request->getHost();

    return redirect()->away("{$scheme}://{$host}/phpmyadmin/jabali-signon.php?token={$token}&db=".urlencode($database));
})->middleware('auth')->name('phpmyadmin.redirect');

// One-time login token for automated testing (generated by: jabali login-token)
Route::get('/auto-login', function (\Illuminate\Http\Request $request) {
    $token = $request->query('token');
    if (! $token || ! is_string($token)) {
        abort(403, 'Missing token');
    }

    $cacheKey = 'login_token:'.hash('sha256', $token);
    $data = Cache::pull($cacheKey); // pull = get + delete (one-time use)

    if (! $data) {
        abort(403, 'Invalid or expired token');
    }

    $user = \App\Models\User::find($data['user_id']);
    if (! $user) {
        abort(403, 'User not found');
    }

    $guard = $user->is_admin ? 'admin' : 'web';
    \Illuminate\Support\Facades\Auth::guard($guard)->login($user);
    session()->regenerate();

    $panel = $data['panel'] ?? ($user->is_admin ? 'admin' : 'user');

    return redirect($panel === 'admin' ? '/jabali-admin/' : '/jabali-panel/');
});

Route::get('/up', function () {
    $checks = [];
    $healthy = true;

    try {
        DB::select('SELECT 1');
        $checks['database'] = 'ok';
    } catch (\Throwable) {
        $checks['database'] = 'fail';
        $healthy = false;
    }

    try {
        Cache::store('redis')->get('health-check');
        $checks['redis'] = 'ok';
    } catch (\Throwable) {
        $checks['redis'] = 'fail';
        $healthy = false;
    }

    return response()->json([
        'status' => $healthy ? 'healthy' : 'degraded',
        'checks' => $checks,
    ], $healthy ? 200 : 503);
});

Route::get('/login', function () {
    return redirect('/jabali-panel/login');
})->name('login');

Route::get('/register', function () {
    return redirect('/jabali-panel/register');
});

// Backward-compatible alias: the "System Updates" page lives at /jabali-admin/server-updates.
Route::redirect('/jabali-admin/system-updates', '/jabali-admin/server-updates');

/*
|--------------------------------------------------------------------------
| Two-Factor Authentication Challenge
|--------------------------------------------------------------------------
*/

Route::get('/jabali-panel/two-factor-challenge', \App\Filament\Jabali\Pages\Auth\TwoFactorChallenge::class)
    ->middleware('web')
    ->name('filament.jabali.auth.two-factor-challenge');

Route::get('/jabali-admin/two-factor-challenge', \App\Filament\Admin\Pages\Auth\TwoFactorChallenge::class)
    ->middleware('web')
    ->name('filament.admin.auth.two-factor-challenge');

/*
|--------------------------------------------------------------------------
| Email Auto-Configuration Routes
|--------------------------------------------------------------------------
|
| These routes handle automatic email client configuration for:
| - Microsoft Outlook (Autodiscover)
| - Mozilla Thunderbird (Autoconfig)
| - iOS/macOS Mail (Mobile Config Profile)
|
*/

// Microsoft Autodiscover (Outlook, Windows Mail, mobile Exchange clients)
Route::match(['get', 'post'], '/autodiscover/autodiscover.xml', [AutoDiscoverController::class, 'discover']);
Route::match(['get', 'post'], '/Autodiscover/Autodiscover.xml', [AutoDiscoverController::class, 'discover']);
Route::match(['get', 'post'], '/AutoDiscover/AutoDiscover.xml', [AutoDiscoverController::class, 'discover']);

// Mozilla Autoconfig (Thunderbird, K-9 Mail, other standards-compliant clients)
Route::get('/mail/config-v1.1.xml', [AutoconfigController::class, 'config']);
Route::get('/.well-known/autoconfig/mail/config-v1.1.xml', [AutoconfigController::class, 'config']);
Route::get('/autoconfig/{domain}/config-v1.1.xml', [AutoconfigController::class, 'configForDomain']);

// iOS/macOS Mobile Configuration Profile
Route::get('/mail/profile/{domain}', [AutoconfigController::class, 'mobileProfile']);

/*
|--------------------------------------------------------------------------
| Admin Impersonation
|--------------------------------------------------------------------------
|
| Allows administrators to login as a user using a one-time token.
| Opens in a new tab with a separate session.
|
*/

Route::post('/impersonate/start/{user}', [ImpersonationController::class, 'start'])
    ->middleware('auth:admin')
    ->name('impersonate.start');

Route::post('/impersonate/stop', [ImpersonationController::class, 'stop'])
    ->middleware('auth:web')
    ->name('impersonate.stop');

Route::get('/impersonate/{token}', [ImpersonationController::class, 'impersonate'])
    ->name('impersonate');

/*
|--------------------------------------------------------------------------
| Language Switcher
|--------------------------------------------------------------------------
*/

Route::get('/language/{locale}', [LanguageController::class, 'switch'])
    ->name('language.switch');

/*
|--------------------------------------------------------------------------
| Webmail SSO
|--------------------------------------------------------------------------
|
| Generates SSO token and redirects to webmail.
| Supports Bulwark (Stalwart backend) and Roundcube (legacy backend).
| Opens in new tab, so uses signed URL for security.
|
*/

Route::get('/webmail-sso/{mailbox}', function (\App\Models\Mailbox $mailbox) {
    // Verify user owns this mailbox
    if ($mailbox->user_id !== auth()->id()) {
        abort(403);
    }

    $ssoDir = config('jabali.sso_token_dir', '/var/lib/jabali/sso-tokens');
    if (! is_dir($ssoDir)) {
        @mkdir($ssoDir, 0700, true);
        if (! is_dir($ssoDir)) {
            // Try via agent (has root access to create system dirs)
            try {
                app(\App\Services\Agent\AgentClient::class)->send('system.ensure_dir', [
                    'path' => $ssoDir,
                    'owner' => 'www-data',
                    'mode' => '0700',
                ]);
            } catch (\Throwable) {
                abort(500, 'SSO token directory could not be created.');
            }
        }
    }

    // Bulwark webmail — SSO via token file
    $token = bin2hex(random_bytes(32));
    $tokenData = [
        'email' => $mailbox->email,
        'expires' => time() + 60,
    ];

    if ($mailbox->plain_password) {
        $tokenData['password'] = $mailbox->plain_password;
        $tokenData['use_direct'] = true;
    }

    $ssoFile = $ssoDir.'/bulwark_sso_'.$token;
    file_put_contents($ssoFile, json_encode($tokenData), LOCK_EX);
    chmod($ssoFile, 0600);

    // Use the same host the user is browsing on so cookies match
    $hostname = request()->getHost();
    $ssoUrl = "https://{$hostname}/webmail/api/auth/sso?token={$token}";

    if (! $mailbox->plain_password) {
        // No stored password - show message about needing to reset password first
        return response()->view('webmail-password-required', [
            'email' => $mailbox->email,
            'mailbox_id' => $mailbox->id,
        ]);
    }

    return redirect($ssoUrl);
})->middleware(['web', 'auth'])->name('webmail.sso');
