-- Jabali Panel: phpMyAdmin user group restrictions
-- The 'panel_users' group hides server-level tabs (Variables, Status, etc.)
-- Users are auto-assigned to this group by jabali-signon.php on SSO login

INSERT IGNORE INTO pma__usergroups (usergroup, tab, allowed) VALUES
  ('panel_users', 'server_databases', 'Y'),
  ('panel_users', 'server_sql', 'Y'),
  ('panel_users', 'server_status', 'N'),
  ('panel_users', 'server_rights', 'N'),
  ('panel_users', 'server_export', 'Y'),
  ('panel_users', 'server_import', 'Y'),
  ('panel_users', 'server_settings', 'N'),
  ('panel_users', 'server_binlog', 'N'),
  ('panel_users', 'server_replication', 'N'),
  ('panel_users', 'server_vars', 'N'),
  ('panel_users', 'server_charset', 'N'),
  ('panel_users', 'server_plugins', 'N'),
  ('panel_users', 'server_engine', 'N'),
  ('panel_users', 'db_structure', 'Y'),
  ('panel_users', 'db_sql', 'Y'),
  ('panel_users', 'db_search', 'Y'),
  ('panel_users', 'db_query', 'Y'),
  ('panel_users', 'db_export', 'Y'),
  ('panel_users', 'db_import', 'Y'),
  ('panel_users', 'db_operation', 'Y'),
  ('panel_users', 'db_privileges', 'N'),
  ('panel_users', 'db_routines', 'Y'),
  ('panel_users', 'db_events', 'Y'),
  ('panel_users', 'db_triggers', 'Y'),
  ('panel_users', 'db_tracking', 'N'),
  ('panel_users', 'table_browse', 'Y'),
  ('panel_users', 'table_structure', 'Y'),
  ('panel_users', 'table_sql', 'Y'),
  ('panel_users', 'table_search', 'Y'),
  ('panel_users', 'table_insert', 'Y'),
  ('panel_users', 'table_export', 'Y'),
  ('panel_users', 'table_import', 'Y'),
  ('panel_users', 'table_operation', 'Y'),
  ('panel_users', 'table_tracking', 'N'),
  ('panel_users', 'table_triggers', 'Y');
