package apps

// invoiceshelfCountryCodes mirrors the 246 rows of InvoiceShelf's
// CountriesTableSeeder (pinned release 2.4.2) — the same list the
// skipped onboarding wizard offers at its company-info step (GH #1042).
// ISO 3166-1 alpha-2 plus the table's few legacy pseudo-codes (XA..XU).
var invoiceshelfCountryCodes = []string{
	"AD", "AE", "AF", "AG", "AI", "AL", "AM", "AN", "AO", "AQ", "AR", "AS", "AT",
	"AU", "AW", "AZ", "BA", "BB", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BM",
	"BN", "BO", "BR", "BS", "BT", "BV", "BW", "BY", "BZ", "CA", "CC", "CD", "CF",
	"CG", "CH", "CI", "CK", "CL", "CM", "CN", "CO", "CR", "CU", "CV", "CX", "CY",
	"CZ", "DE", "DJ", "DK", "DM", "DO", "DZ", "EC", "EE", "EG", "EH", "ER", "ES",
	"ET", "FI", "FJ", "FK", "FM", "FO", "FR", "GA", "GB", "GD", "GE", "GF", "GH",
	"GI", "GL", "GM", "GN", "GP", "GQ", "GR", "GS", "GT", "GU", "GW", "GY", "HK",
	"HM", "HN", "HR", "HT", "HU", "ID", "IE", "IL", "IN", "IO", "IQ", "IR", "IS",
	"IT", "JM", "JO", "JP", "KE", "KG", "KH", "KI", "KM", "KN", "KP", "KR", "KW",
	"KY", "KZ", "LA", "LB", "LC", "LI", "LK", "LR", "LS", "LT", "LU", "LV", "LY",
	"MA", "MC", "MD", "MG", "MH", "MK", "ML", "MM", "MN", "MO", "MP", "MQ", "MR",
	"MS", "MT", "MU", "MV", "MW", "MX", "MY", "MZ", "NA", "NC", "NE", "NF", "NG",
	"NI", "NL", "NO", "NP", "NR", "NU", "NZ", "OM", "PA", "PE", "PF", "PG", "PH",
	"PK", "PL", "PM", "PN", "PR", "PS", "PT", "PW", "PY", "QA", "RE", "RO", "RS",
	"RU", "RW", "SA", "SB", "SC", "SD", "SE", "SG", "SH", "SI", "SJ", "SK", "SL",
	"SM", "SN", "SO", "SR", "SS", "ST", "SV", "SY", "SZ", "TC", "TD", "TF", "TG",
	"TH", "TJ", "TK", "TM", "TN", "TO", "TP", "TR", "TT", "TV", "TW", "TZ", "UA",
	"UG", "UM", "US", "UY", "UZ", "VA", "VC", "VE", "VG", "VI", "VN", "VU", "WF",
	"WS", "XA", "XG", "XJ", "XM", "XU", "YE", "YT", "YU", "ZA", "ZM", "ZW",
}

// invoiceshelfCountryLabels renders the enum as "Name (CODE)" so the
// searchable Select matches on the country NAME, not just the code —
// with 246 entries code-only search is unusable.
var invoiceshelfCountryLabels = map[string]string{
	"AD": "Andorra (AD)",
	"AE": "United Arab Emirates (AE)",
	"AF": "Afghanistan (AF)",
	"AG": "Antigua And Barbuda (AG)",
	"AI": "Anguilla (AI)",
	"AL": "Albania (AL)",
	"AM": "Armenia (AM)",
	"AN": "Netherlands Antilles (AN)",
	"AO": "Angola (AO)",
	"AQ": "Antarctica (AQ)",
	"AR": "Argentina (AR)",
	"AS": "American Samoa (AS)",
	"AT": "Austria (AT)",
	"AU": "Australia (AU)",
	"AW": "Aruba (AW)",
	"AZ": "Azerbaijan (AZ)",
	"BA": "Bosnia and Herzegovina (BA)",
	"BB": "Barbados (BB)",
	"BD": "Bangladesh (BD)",
	"BE": "Belgium (BE)",
	"BF": "Burkina Faso (BF)",
	"BG": "Bulgaria (BG)",
	"BH": "Bahrain (BH)",
	"BI": "Burundi (BI)",
	"BJ": "Benin (BJ)",
	"BM": "Bermuda (BM)",
	"BN": "Brunei (BN)",
	"BO": "Bolivia (BO)",
	"BR": "Brazil (BR)",
	"BS": "Bahamas The (BS)",
	"BT": "Bhutan (BT)",
	"BV": "Bouvet Island (BV)",
	"BW": "Botswana (BW)",
	"BY": "Belarus (BY)",
	"BZ": "Belize (BZ)",
	"CA": "Canada (CA)",
	"CC": "Cocos (Keeling) Islands (CC)",
	"CD": "Congo The Democratic Republic Of The (CD)",
	"CF": "Central African Republic (CF)",
	"CG": "Congo (CG)",
	"CH": "Switzerland (CH)",
	"CI": "Cote D Ivoire (Ivory Coast) (CI)",
	"CK": "Cook Islands (CK)",
	"CL": "Chile (CL)",
	"CM": "Cameroon (CM)",
	"CN": "China (CN)",
	"CO": "Colombia (CO)",
	"CR": "Costa Rica (CR)",
	"CU": "Cuba (CU)",
	"CV": "Cape Verde (CV)",
	"CX": "Christmas Island (CX)",
	"CY": "Cyprus (CY)",
	"CZ": "Czech Republic (CZ)",
	"DE": "Germany (DE)",
	"DJ": "Djibouti (DJ)",
	"DK": "Denmark (DK)",
	"DM": "Dominica (DM)",
	"DO": "Dominican Republic (DO)",
	"DZ": "Algeria (DZ)",
	"EC": "Ecuador (EC)",
	"EE": "Estonia (EE)",
	"EG": "Egypt (EG)",
	"EH": "Western Sahara (EH)",
	"ER": "Eritrea (ER)",
	"ES": "Spain (ES)",
	"ET": "Ethiopia (ET)",
	"FI": "Finland (FI)",
	"FJ": "Fiji Islands (FJ)",
	"FK": "Falkland Islands (FK)",
	"FM": "Micronesia (FM)",
	"FO": "Faroe Islands (FO)",
	"FR": "France (FR)",
	"GA": "Gabon (GA)",
	"GB": "United Kingdom (GB)",
	"GD": "Grenada (GD)",
	"GE": "Georgia (GE)",
	"GF": "French Guiana (GF)",
	"GH": "Ghana (GH)",
	"GI": "Gibraltar (GI)",
	"GL": "Greenland (GL)",
	"GM": "Gambia The (GM)",
	"GN": "Guinea (GN)",
	"GP": "Guadeloupe (GP)",
	"GQ": "Equatorial Guinea (GQ)",
	"GR": "Greece (GR)",
	"GS": "South Georgia (GS)",
	"GT": "Guatemala (GT)",
	"GU": "Guam (GU)",
	"GW": "Guinea-Bissau (GW)",
	"GY": "Guyana (GY)",
	"HK": "Hong Kong S.A.R. (HK)",
	"HM": "Heard and McDonald Islands (HM)",
	"HN": "Honduras (HN)",
	"HR": "Croatia (Hrvatska) (HR)",
	"HT": "Haiti (HT)",
	"HU": "Hungary (HU)",
	"ID": "Indonesia (ID)",
	"IE": "Ireland (IE)",
	"IL": "Israel (IL)",
	"IN": "India (IN)",
	"IO": "British Indian Ocean Territory (IO)",
	"IQ": "Iraq (IQ)",
	"IR": "Iran (IR)",
	"IS": "Iceland (IS)",
	"IT": "Italy (IT)",
	"JM": "Jamaica (JM)",
	"JO": "Jordan (JO)",
	"JP": "Japan (JP)",
	"KE": "Kenya (KE)",
	"KG": "Kyrgyzstan (KG)",
	"KH": "Cambodia (KH)",
	"KI": "Kiribati (KI)",
	"KM": "Comoros (KM)",
	"KN": "Saint Kitts And Nevis (KN)",
	"KP": "Korea North (KP)",
	"KR": "Korea South (KR)",
	"KW": "Kuwait (KW)",
	"KY": "Cayman Islands (KY)",
	"KZ": "Kazakhstan (KZ)",
	"LA": "Laos (LA)",
	"LB": "Lebanon (LB)",
	"LC": "Saint Lucia (LC)",
	"LI": "Liechtenstein (LI)",
	"LK": "Sri Lanka (LK)",
	"LR": "Liberia (LR)",
	"LS": "Lesotho (LS)",
	"LT": "Lithuania (LT)",
	"LU": "Luxembourg (LU)",
	"LV": "Latvia (LV)",
	"LY": "Libya (LY)",
	"MA": "Morocco (MA)",
	"MC": "Monaco (MC)",
	"MD": "Moldova (MD)",
	"MG": "Madagascar (MG)",
	"MH": "Marshall Islands (MH)",
	"MK": "Macedonia (MK)",
	"ML": "Mali (ML)",
	"MM": "Myanmar (MM)",
	"MN": "Mongolia (MN)",
	"MO": "Macau S.A.R. (MO)",
	"MP": "Northern Mariana Islands (MP)",
	"MQ": "Martinique (MQ)",
	"MR": "Mauritania (MR)",
	"MS": "Montserrat (MS)",
	"MT": "Malta (MT)",
	"MU": "Mauritius (MU)",
	"MV": "Maldives (MV)",
	"MW": "Malawi (MW)",
	"MX": "Mexico (MX)",
	"MY": "Malaysia (MY)",
	"MZ": "Mozambique (MZ)",
	"NA": "Namibia (NA)",
	"NC": "New Caledonia (NC)",
	"NE": "Niger (NE)",
	"NF": "Norfolk Island (NF)",
	"NG": "Nigeria (NG)",
	"NI": "Nicaragua (NI)",
	"NL": "Netherlands (NL)",
	"NO": "Norway (NO)",
	"NP": "Nepal (NP)",
	"NR": "Nauru (NR)",
	"NU": "Niue (NU)",
	"NZ": "New Zealand (NZ)",
	"OM": "Oman (OM)",
	"PA": "Panama (PA)",
	"PE": "Peru (PE)",
	"PF": "French Polynesia (PF)",
	"PG": "Papua new Guinea (PG)",
	"PH": "Philippines (PH)",
	"PK": "Pakistan (PK)",
	"PL": "Poland (PL)",
	"PM": "Saint Pierre and Miquelon (PM)",
	"PN": "Pitcairn Island (PN)",
	"PR": "Puerto Rico (PR)",
	"PS": "Palestinian Territory Occupied (PS)",
	"PT": "Portugal (PT)",
	"PW": "Palau (PW)",
	"PY": "Paraguay (PY)",
	"QA": "Qatar (QA)",
	"RE": "Reunion (RE)",
	"RO": "Romania (RO)",
	"RS": "Serbia (RS)",
	"RU": "Russia (RU)",
	"RW": "Rwanda (RW)",
	"SA": "Saudi Arabia (SA)",
	"SB": "Solomon Islands (SB)",
	"SC": "Seychelles (SC)",
	"SD": "Sudan (SD)",
	"SE": "Sweden (SE)",
	"SG": "Singapore (SG)",
	"SH": "Saint Helena (SH)",
	"SI": "Slovenia (SI)",
	"SJ": "Svalbard And Jan Mayen Islands (SJ)",
	"SK": "Slovakia (SK)",
	"SL": "Sierra Leone (SL)",
	"SM": "San Marino (SM)",
	"SN": "Senegal (SN)",
	"SO": "Somalia (SO)",
	"SR": "Suriname (SR)",
	"SS": "South Sudan (SS)",
	"ST": "Sao Tome and Principe (ST)",
	"SV": "El Salvador (SV)",
	"SY": "Syria (SY)",
	"SZ": "Swaziland (SZ)",
	"TC": "Turks And Caicos Islands (TC)",
	"TD": "Chad (TD)",
	"TF": "French Southern Territories (TF)",
	"TG": "Togo (TG)",
	"TH": "Thailand (TH)",
	"TJ": "Tajikistan (TJ)",
	"TK": "Tokelau (TK)",
	"TM": "Turkmenistan (TM)",
	"TN": "Tunisia (TN)",
	"TO": "Tonga (TO)",
	"TP": "East Timor (TP)",
	"TR": "Turkey (TR)",
	"TT": "Trinidad And Tobago (TT)",
	"TV": "Tuvalu (TV)",
	"TW": "Taiwan (TW)",
	"TZ": "Tanzania (TZ)",
	"UA": "Ukraine (UA)",
	"UG": "Uganda (UG)",
	"UM": "United States Minor Outlying Islands (UM)",
	"US": "United States (US)",
	"UY": "Uruguay (UY)",
	"UZ": "Uzbekistan (UZ)",
	"VA": "Vatican City State (Holy See) (VA)",
	"VC": "Saint Vincent And The Grenadines (VC)",
	"VE": "Venezuela (VE)",
	"VG": "Virgin Islands (British) (VG)",
	"VI": "Virgin Islands (US) (VI)",
	"VN": "Vietnam (VN)",
	"VU": "Vanuatu (VU)",
	"WF": "Wallis And Futuna Islands (WF)",
	"WS": "Samoa (WS)",
	"XA": "External Territories of Australia (XA)",
	"XG": "Smaller Territories of the UK (XG)",
	"XJ": "Jersey (XJ)",
	"XM": "Man (Isle of) (XM)",
	"XU": "Guernsey and Alderney (XU)",
	"YE": "Yemen (YE)",
	"YT": "Mayotte (YT)",
	"YU": "Yugoslavia (YU)",
	"ZA": "South Africa (ZA)",
	"ZM": "Zambia (ZM)",
	"ZW": "Zimbabwe (ZW)",
}
