---
env:
  contexts:
    - name: "Jabali Panel"
      urls:
        - "https://10.0.3.13"
      includePaths:
        - "https://10.0.3.13/jabali-admin.*"
        - "https://10.0.3.13/jabali-panel.*"
        - "https://10.0.3.13/api.*"
        - "https://10.0.3.13/livewire.*"
      excludePaths:
        - "https://10.0.3.13/build/.*"
        - "https://10.0.3.13/vendor/.*"
        - "https://10.0.3.13/favicon.ico"
  parameters:
    failOnError: false
    failOnWarning: false

jobs:
  - type: spider
    parameters:
      context: "Jabali Panel"
      maxDuration: 5
      maxDepth: 5
      maxChildren: 20

  - type: spiderAjax
    parameters:
      context: "Jabali Panel"
      maxDuration: 5
      maxCrawlDepth: 3

  - type: passiveScan-wait
    parameters:
      maxDuration: 5

  - type: activeScan
    parameters:
      context: "Jabali Panel"
      maxRuleDurationInMins: 2
      maxScanDurationInMins: 30
      policy: "Default Policy"

  - type: report
    parameters:
      template: "traditional-html"
      reportDir: "/zap/wrk"
      reportFile: "jabali-zap-report"
    risks:
      - high
      - medium
      - low
      - info
