package commands

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// GH #1701: the per-domain PHP values (PHP_VALUE, PHP_ADMIN_VALUE and the
// domain's environment variables) reach PHP-FPM only from a location that
// sends them, and a value sent once sticks on the reused worker for the next
// request that sends none. The vhost's own PHP locations send them; the PHP
// locations of the per-install app snippets in /etc/nginx/jabali/<domain>/
// (Drupal/Joomla/OpenEMR/InvoiceShelf/Flarum subdir installs, the osTicket
// PATH_INFO handler) did not. A request there ran with whatever the previous
// request on that worker left behind: a sibling domain's display_errors=On,
// or its narrowed open_basedir, which breaks the app.
//
// So writeVhost keeps a php-pins.params file beside the snippets with the same
// fastcgi_param lines as the vhost's PHP locations, and every snippet PHP
// location includes it. The include is a glob, so nginx accepts it before the
// file exists (a fresh install before the next vhost write). Snippets written
// before this change get the include added by writeVhost.

const phpPinsFileName = "php-pins.params"

// phpPinsInclude is the include line a snippet's PHP location carries.
func phpPinsInclude(domain string) string {
	return "include " + filepath.Join(nginxJabaliDir, domain, "php-pins*.params") + ";"
}

// renderPHPPinParams renders the per-domain PHP fastcgi_param lines of a
// vhost, exactly as its PHP locations carry them. "" for a non-PHP vhost.
func renderPHPPinParams(vd vhostData) string {
	if !vd.HasPHP {
		return ""
	}
	var b strings.Builder
	if vd.PHPValueParam != "" {
		b.WriteString("fastcgi_param PHP_VALUE \"" + vd.PHPValueParam + "\";\n")
	}
	if vd.PHPAdminValueParam != "" {
		b.WriteString("fastcgi_param PHP_ADMIN_VALUE \"" + vd.PHPAdminValueParam + "\";\n")
	}
	if vd.EnvParams != "" {
		b.WriteString(vd.EnvParams + "\n")
	}
	return b.String()
}

// pinFileChange is one file writeVhost writes (or removes) beside the
// snippets, with what was there before so a failed nginx -t can put it back.
type pinFileChange struct {
	path    string
	want    []byte
	remove  bool
	prev    []byte
	existed bool
}

// planPHPPinFiles returns the changes that bring dir (/etc/nginx/jabali/<domain>)
// in line: the pins file holds params (removed when the vhost has no PHP), and
// every snippet PHP location includes it. Nothing when all is already so.
func planPHPPinFiles(dir, domain string, params string) []pinFileChange {
	var out []pinFileChange
	pinsPath := filepath.Join(dir, phpPinsFileName)
	prev, err := os.ReadFile(pinsPath)
	existed := err == nil
	if params != "" {
		want := []byte("# Auto-generated by jabali-agent. Do not edit.\n" +
			"# " + domain + "'s per-domain PHP values (GH #1701), included by the PHP\n" +
			"# locations of the app snippets in this directory.\n" + params)
		if !existed || !bytes.Equal(prev, want) {
			out = append(out, pinFileChange{path: pinsPath, want: want, prev: prev, existed: existed})
		}
	} else if existed {
		out = append(out, pinFileChange{path: pinsPath, remove: true, prev: prev, existed: true})
	}

	snippets, _ := filepath.Glob(filepath.Join(dir, "*.conf"))
	sort.Strings(snippets)
	for _, p := range snippets {
		if fi, err := os.Lstat(p); err != nil || !fi.Mode().IsRegular() {
			continue
		}
		body, err := os.ReadFile(p)
		if err != nil {
			continue
		}
		if patched, ok := withPHPPinsInclude(body, domain); ok {
			out = append(out, pinFileChange{path: p, want: patched, prev: body, existed: true})
		}
	}
	return out
}

// withPHPPinsInclude adds the pins include after every `include
// fastcgi_params;` of a snippet that passes to PHP-FPM. A snippet that
// already includes the pins, or sets its own PHP_VALUE / PHP_ADMIN_VALUE (an
// operator's hand-written one), is left alone.
func withPHPPinsInclude(body []byte, domain string) ([]byte, bool) {
	s := string(body)
	if !strings.Contains(s, "fastcgi_pass") || strings.Contains(s, "php-pins") ||
		strings.Contains(s, "PHP_VALUE") || strings.Contains(s, "PHP_ADMIN_VALUE") {
		return nil, false
	}
	var b strings.Builder
	changed := false
	for _, l := range strings.SplitAfter(s, "\n") {
		b.WriteString(l)
		if strings.TrimSpace(l) != "include fastcgi_params;" {
			continue
		}
		if !strings.HasSuffix(l, "\n") {
			b.WriteString("\n")
		}
		indent := l[:len(l)-len(strings.TrimLeft(l, " \t"))]
		b.WriteString(indent + phpPinsInclude(domain) + "\n")
		changed = true
	}
	if !changed {
		return nil, false
	}
	return []byte(b.String()), true
}

// snippetWithPHPPins is an app snippet as written at install: with the pins
// include in its PHP locations, so it is pinned from the first request.
func snippetWithPHPPins(body []byte, domain string) []byte {
	if patched, ok := withPHPPinsInclude(body, domain); ok {
		return patched
	}
	return body
}

// applyPinFileChanges writes the changes atomically, creating the directory
// for a new pins file. On a failure it puts back what it already changed.
func applyPinFileChanges(changes []pinFileChange) error {
	for i, c := range changes {
		var err error
		if c.remove {
			err = os.Remove(c.path)
		} else if err = os.MkdirAll(filepath.Dir(c.path), 0o755); err == nil {
			err = writeFileAtomic(c.path, c.want, 0o644)
		}
		if err != nil {
			revertPinFileChanges(changes[:i])
			return fmt.Errorf("php pins %s: %w", c.path, err)
		}
	}
	return nil
}

// revertPinFileChanges restores what each change replaced, or removes a file
// it created.
func revertPinFileChanges(changes []pinFileChange) {
	for _, c := range changes {
		if c.existed {
			_ = writeFileAtomic(c.path, c.prev, 0o644)
		} else {
			_ = os.Remove(c.path)
		}
	}
}
