<?php

declare(strict_types=1);

namespace App\Support;

class WordList
{
    /**
     * @return list<string>
     */
    public static function random(int $count = 3): array
    {
        $words = static::words();
        $selected = [];
        for ($i = 0; $i < $count; $i++) {
            $selected[] = $words[random_int(0, count($words) - 1)];
        }

        return $selected;
    }

    public static function generate(int $wordCount = 3, string $separator = '-'): string
    {
        return implode($separator, static::random($wordCount));
    }

    /**
     * Curated word list: fruits, vegetables, animals, happy words, and names.
     *
     * @return list<string>
     */
    /** @var list<string>|null */
    private static ?array $cached = null;

    private static function words(): array
    {
        if (static::$cached !== null) {
            return static::$cached;
        }

        static::$cached = array_values(array_unique([
            // ── Fruits & vegetables ────────────────────────────────────
            'acai', 'apple', 'apricot', 'artichoke', 'arugula', 'asparagus',
            'avocado', 'bamboo', 'banana', 'basil', 'bean', 'beet',
            'berry', 'bokchoy', 'boysenberry', 'broccoli', 'butternut', 'cabbage',
            'cantaloupe', 'carrot', 'cassava', 'cauliflower', 'celery', 'chard',
            'cherry', 'chickpea', 'chili', 'chive', 'cilantro', 'citron',
            'clementine', 'coconut', 'collard', 'coriander', 'corn', 'crabapple',
            'cranberry', 'cress', 'cucumber', 'cumin', 'currant', 'daikon',
            'damson', 'date', 'dill', 'dragonfruit', 'durian', 'edamame',
            'eggplant', 'elderberry', 'endive', 'fava', 'fennel', 'fig',
            'garlic', 'ginger', 'gooseberry', 'grape', 'grapefruit', 'guava',
            'habanero', 'honeydew', 'horseradish', 'huckleberry', 'jackfruit', 'jalapeno',
            'jicama', 'jujube', 'kale', 'kiwi', 'kohlrabi', 'kumquat',
            'lavender', 'leek', 'lemon', 'lentil', 'lettuce', 'lime',
            'longan', 'loquat', 'lotus', 'lychee', 'mandarin', 'mango',
            'mangosteen', 'marjoram', 'medlar', 'melon', 'mint', 'mulberry',
            'mushroom', 'mustard', 'nectarine', 'nutmeg', 'okra', 'olive',
            'onion', 'orange', 'oregano', 'papaya', 'paprika', 'parsley',
            'parsnip', 'passion', 'peach', 'pea', 'pear', 'pepper',
            'persimmon', 'pineapple', 'pitaya', 'plantain', 'plum', 'pomegranate',
            'pomelo', 'potato', 'prune', 'pumpkin', 'quince', 'quinoa',
            'radish', 'radicchio', 'raisin', 'rambutan', 'raspberry', 'rhubarb',
            'rosemary', 'rutabaga', 'saffron', 'sage', 'salak', 'sapote',
            'scallion', 'sesame', 'shallot', 'sorrel', 'soursop', 'soybean',
            'spinach', 'sprout', 'squash', 'starfruit', 'strawberry', 'tamarind',
            'tangerine', 'taro', 'tarragon', 'thyme', 'tomato', 'turmeric',
            'turnip', 'vanilla', 'verbena', 'wasabi', 'watercress', 'watermelon',
            'yam', 'yuzu', 'zucchini',

            // ── Animals ────────────────────────────────────────────────
            'albatross', 'alligator', 'alpaca', 'angelfish', 'ant', 'anteater',
            'antelope', 'armadillo', 'baboon', 'badger', 'barracuda', 'bat',
            'bear', 'beaver', 'beetle', 'bison', 'bluebird', 'bluejay',
            'bobcat', 'buffalo', 'bunny', 'butterfly', 'camel', 'canary',
            'cardinal', 'caribou', 'catfish', 'chameleon', 'cheetah', 'chickadee',
            'chipmunk', 'clam', 'cobra', 'cockatoo', 'condor', 'coral',
            'corgi', 'cougar', 'cow', 'coyote', 'crab', 'crane',
            'cricket', 'crocodile', 'crow', 'cub', 'cuckoo', 'dalmatian',
            'deer', 'dingo', 'doe', 'dolphin', 'donkey', 'dove',
            'dragonfly', 'duck', 'eagle', 'eel', 'egret', 'elephant',
            'elk', 'emu', 'ermine', 'falcon', 'fawn', 'ferret',
            'finch', 'firefly', 'flamingo', 'flounder', 'fox', 'frog',
            'gazelle', 'gecko', 'gerbil', 'giraffe', 'goat', 'goldfinch',
            'goose', 'gorilla', 'grasshopper', 'grizzly', 'grouper', 'grouse',
            'gull', 'hamster', 'hare', 'hawk', 'hedgehog', 'heron',
            'hippo', 'horse', 'hound', 'hummingbird', 'husky', 'hyena',
            'ibis', 'iguana', 'impala', 'jackal', 'jaguar', 'jay',
            'jellyfish', 'kangaroo', 'kestrel', 'kingfisher', 'kitten', 'koala',
            'ladybug', 'lamb', 'lark', 'lemur', 'leopard', 'lion',
            'lizard', 'llama', 'lobster', 'loon', 'lynx', 'macaw',
            'magpie', 'mammoth', 'manatee', 'mantis', 'marlin', 'marmot',
            'meerkat', 'mockingbird', 'mongoose', 'monkey', 'moose', 'moth',
            'mouse', 'mule', 'narwhal', 'newt', 'nightingale', 'ocelot',
            'octopus', 'okapi', 'opossum', 'orangutan', 'orca', 'oriole',
            'osprey', 'ostrich', 'otter', 'owl', 'ox', 'oyster',
            'panda', 'panther', 'parakeet', 'parrot', 'partridge', 'peacock',
            'pelican', 'penguin', 'perch', 'pheasant', 'pig', 'pigeon',
            'pike', 'platypus', 'pony', 'poodle', 'porcupine', 'porpoise',
            'possum', 'puffin', 'puma', 'puppy', 'quail', 'rabbit',
            'raccoon', 'ram', 'raven', 'reindeer', 'rhino', 'roadrunner',
            'robin', 'rooster', 'sailfish', 'salamander', 'salmon', 'sandpiper',
            'sardine', 'seahorse', 'seal', 'shark', 'sheep', 'shrimp',
            'skunk', 'sloth', 'snail', 'snake', 'snapper', 'sparrow',
            'squid', 'squirrel', 'stallion', 'starfish', 'starling', 'stingray',
            'stork', 'sturgeon', 'swan', 'swift', 'swordfish', 'tapir',
            'tarpon', 'terrier', 'thrush', 'tiger', 'toad', 'toucan',
            'trout', 'tuna', 'turkey', 'turtle', 'unicorn', 'viper',
            'vulture', 'walrus', 'warbler', 'weasel', 'whale', 'wolf',
            'wolverine', 'wombat', 'woodpecker', 'wren', 'yak', 'zebra',

            // ── Happy words ────────────────────────────────────────────
            'admire', 'adore', 'adventure', 'amazing', 'angel', 'awesome',
            'balance', 'beauty', 'believe', 'beloved', 'best', 'bliss',
            'bloom', 'blossom', 'bold', 'bonus', 'bounce', 'brave',
            'breeze', 'bright', 'brilliant', 'bubbly', 'calm', 'carefree',
            'caring', 'celebrate', 'champion', 'charm', 'cheer', 'cheerful',
            'chime', 'classic', 'clever', 'comfort', 'cozy', 'create',
            'creative', 'crystal', 'cuddle', 'dance', 'daring', 'dawn',
            'dazzle', 'dear', 'delight', 'diamond', 'discover', 'divine',
            'dream', 'dreamy', 'easy', 'elegant', 'embrace', 'emerald',
            'enchant', 'energy', 'enjoy', 'epic', 'evergreen', 'excited',
            'explore', 'fabulous', 'fair', 'faith', 'fame', 'fancy',
            'fantastic', 'festive', 'fierce', 'fizzy', 'flair', 'floral',
            'flourish', 'flutter', 'fortune', 'free', 'freedom', 'fresh',
            'friend', 'friendly', 'frolic', 'frost', 'fun', 'funky',
            'gala', 'garden', 'gem', 'generous', 'genius', 'gentle',
            'gift', 'giggle', 'glad', 'glamour', 'gleam', 'glee',
            'glitter', 'glow', 'golden', 'good', 'grace', 'grand',
            'grateful', 'great', 'grin', 'groove', 'grow', 'guide',
            'happy', 'harbor', 'harmony', 'harvest', 'haven', 'heart',
            'hello', 'hero', 'holiday', 'honest', 'honey', 'honor',
            'hooray', 'hope', 'hug', 'humble', 'hustle', 'imagine',
            'infinity', 'inspire', 'island', 'jewel', 'jolly', 'journey',
            'jovial', 'joy', 'joyful', 'jubilant', 'jubilee', 'juice',
            'jump', 'keen', 'kind', 'kindred', 'kiss', 'kudos',
            'laugh', 'lavish', 'legacy', 'legend', 'liberty', 'light',
            'lively', 'love', 'lovely', 'loyal', 'luck', 'lucky',
            'lush', 'magic', 'majestic', 'marble', 'marvel', 'mellow',
            'melody', 'merry', 'mighty', 'miracle', 'mirth', 'mist',
            'moonbeam', 'morning', 'nectar', 'nice', 'noble', 'nurture',
            'oasis', 'ocean', 'open', 'optimist', 'organic', 'original',
            'ovation', 'paradise', 'party', 'patient', 'peace', 'peachy',
            'perfect', 'petal', 'pioneer', 'playful', 'pleasant', 'plucky',
            'polish', 'popular', 'positive', 'power', 'precious', 'pride',
            'promise', 'prosper', 'proud', 'pure', 'purple', 'quest',
            'quick', 'quiet', 'radiant', 'rainbow', 'rejoice', 'relax',
            'renew', 'respect', 'rhythm', 'ribbon', 'rich', 'rise',
            'river', 'rosy', 'royal', 'ruby', 'sacred', 'safe',
            'sapphire', 'scenic', 'serene', 'shimmer', 'shine', 'silver',
            'simple', 'sincere', 'sky', 'smart', 'smile', 'smooth',
            'snuggle', 'soar', 'soft', 'solar', 'soul', 'spark',
            'sparkle', 'special', 'spirit', 'splash', 'spring', 'star',
            'stellar', 'strong', 'success', 'summer', 'summit', 'sun',
            'sunny', 'sunrise', 'sunset', 'super', 'sweet', 'tender',
            'thankful', 'thrive', 'tidal', 'topaz', 'treasure', 'triumph',
            'tropical', 'true', 'trust', 'truth', 'tulip', 'twinkle',
            'unity', 'uplift', 'valor', 'velvet', 'vibrant', 'victory',
            'vigor', 'virtue', 'vivid', 'voyage', 'warm', 'wave',
            'welcome', 'whole', 'wild', 'willing', 'wind', 'wings',
            'winner', 'winter', 'wisdom', 'wish', 'wonder', 'wonderful',
            'worthy', 'wow', 'zeal', 'zen', 'zephyr', 'zest',
            'zing', 'zippy', 'zone',

            // ── Names ──────────────────────────────────────────────────
            'abel', 'ada', 'adam', 'adele', 'adrian', 'agatha',
            'aiden', 'alana', 'albert', 'alder', 'alex', 'alice',
            'alma', 'amara', 'amber', 'amelia', 'amir', 'amos',
            'amy', 'andre', 'andrew', 'angela', 'anna', 'anton',
            'april', 'archer', 'aria', 'ariel', 'arnold', 'arthur',
            'asher', 'astrid', 'atlas', 'aubrey', 'audrey', 'aurora',
            'austin', 'autumn', 'axel', 'ayden', 'bailey', 'baron',
            'beatrice', 'beau', 'beckett', 'bella', 'benedict', 'benjamin',
            'bennett', 'benny', 'bertha', 'bethany', 'bianca', 'blake',
            'blanca', 'bonnie', 'boris', 'brad', 'brandon', 'brenda',
            'brett', 'brian', 'bridget', 'brooke', 'bruce', 'bruno',
            'bryce', 'byron', 'caleb', 'calvin', 'camila', 'cara',
            'carey', 'carla', 'carlos', 'carmen', 'carol', 'carter',
            'casey', 'cedar', 'celeste', 'chad', 'chance', 'charles',
            'charlie', 'chase', 'chelsea', 'chester', 'chloe', 'clara',
            'clarence', 'clark', 'claude', 'clay', 'cleo', 'cliff',
            'clint', 'clover', 'cody', 'cole', 'colin', 'colton',
            'connor', 'cooper', 'cora', 'corey', 'craig', 'curtis',
            'cyrus', 'dahlia', 'daisy', 'dale', 'dallas', 'dalton',
            'dana', 'daniel', 'daphne', 'dario', 'darla', 'darwin',
            'david', 'dean', 'deanna', 'declan', 'delia', 'denis',
            'derek', 'desmond', 'devon', 'diana', 'diego', 'dominic',
            'donald', 'donna', 'dorian', 'dorothy', 'drew', 'dulce',
            'duncan', 'dustin', 'dylan', 'eden', 'edgar', 'edith',
            'edmund', 'edward', 'elaine', 'elena', 'eli', 'elias',
            'elijah', 'elise', 'ella', 'ellen', 'elliott', 'eloise',
            'elsa', 'ember', 'emery', 'emily', 'emma', 'emmett',
            'enrique', 'eric', 'ernest', 'esme', 'esther', 'ethan',
            'eunice', 'eva', 'evan', 'evelyn', 'everett', 'ezra',
            'farah', 'fatima', 'faye', 'felicia', 'felix', 'fern',
            'fernando', 'fiona', 'fletcher', 'flora', 'florence', 'flynn',
            'forest', 'forrest', 'foster', 'frances', 'frank', 'franklin',
            'fraser', 'freya', 'frida', 'fritz', 'gabriel', 'gael',
            'gaia', 'garrett', 'gavin', 'gemma', 'george', 'georgia',
            'gerald', 'gideon', 'gina', 'glen', 'gloria', 'gordon',
            'graham', 'grant', 'greta', 'griffin', 'gunnar', 'gustav',
            'gwen', 'hailey', 'hank', 'hannah', 'hans', 'harlan',
            'harley', 'harold', 'harper', 'harriet', 'harrison', 'harry',
            'harvey', 'hazel', 'heath', 'heather', 'hector', 'heidi',
            'helen', 'henry', 'herman', 'hilda', 'holly', 'homer',
            'howard', 'hubert', 'hudson', 'hugo', 'hunter', 'ida',
            'ignacio', 'ingrid', 'irene', 'iris', 'irving', 'isaac',
            'isabel', 'isaiah', 'ivan', 'ivy', 'jack', 'jacob',
            'jade', 'james', 'jamie', 'jane', 'jared', 'jasmine',
            'jasper', 'javier', 'jean', 'jenna', 'jenny', 'jeremy',
            'jesse', 'jessica', 'jethro', 'joel', 'johanna', 'john',
            'jonas', 'jonathan', 'jordan', 'jose', 'joseph', 'josie',
            'juan', 'judith', 'julia', 'julian', 'juliet', 'june',
            'juniper', 'justin', 'kai', 'kara', 'karen', 'karl',
            'kate', 'katrina', 'kayla', 'keegan', 'keith', 'kelly',
            'kelsey', 'kendall', 'kennedy', 'kent', 'kerry', 'kevin',
            'kian', 'kira', 'kirk', 'klaus', 'knox', 'kyle',
            'lana', 'lance', 'landon', 'lara', 'larissa', 'lars',
            'laura', 'lauren', 'lawrence', 'layla', 'leah', 'leon',
            'leonard', 'leroy', 'leslie', 'levi', 'lewis', 'liam',
            'lila', 'lily', 'lina', 'linda', 'linus', 'lionel',
            'lisa', 'logan', 'lola', 'london', 'lorraine', 'louisa',
            'lucas', 'lucia', 'lucian', 'lucy', 'luis', 'luke',
            'luna', 'luther', 'lydia', 'lynn', 'mabel', 'madeline',
            'madison', 'magnus', 'maia', 'malcolm', 'malik', 'mallory',
            'mara', 'marcel', 'marco', 'marcus', 'margaret', 'maria',
            'marina', 'mario', 'marissa', 'mark', 'marlene', 'martha',
            'martin', 'marvin', 'mason', 'mateo', 'mathew', 'matilda',
            'max', 'maxine', 'maya', 'melanie', 'melissa', 'mercer',
            'mia', 'michael', 'miguel', 'mila', 'miles', 'miller',
            'milo', 'mina', 'miranda', 'mitchell', 'molly', 'monica',
            'morgan', 'morris', 'moses', 'murphy', 'nadia', 'nancy',
            'naomi', 'natalie', 'nathan', 'neal', 'neil', 'nelly',
            'nelson', 'nero', 'nestor', 'neva', 'nicholas', 'nicole',
            'nina', 'noah', 'noel', 'nolan', 'nora', 'norma',
            'norman', 'nova', 'oliver', 'olivia', 'omar', 'opal',
            'ophelia', 'orion', 'orlando', 'oscar', 'otto', 'owen',
            'paige', 'palmer', 'pamela', 'paolo', 'parker', 'pascal',
            'patricia', 'patrick', 'paul', 'paula', 'pedro', 'penny',
            'percy', 'peter', 'petra', 'philip', 'phoenix', 'pierce',
            'porter', 'priya', 'prudence', 'quentin', 'quinn', 'rafael',
            'raina', 'ralph', 'ramona', 'randall', 'raquel', 'ray',
            'raymond', 'reagan', 'rebecca', 'reed', 'regina', 'remy',
            'renata', 'rene', 'rex', 'rhea', 'richard', 'riley',
            'rita', 'robert', 'rocco', 'roger', 'roman', 'romeo',
            'ronald', 'rosa', 'rosalie', 'rose', 'ross', 'rowan',
            'roxanne', 'roy', 'ruben', 'rufus', 'russell', 'ruth',
            'ryan', 'sabrina', 'sadie', 'sally', 'salma', 'sam',
            'samantha', 'samuel', 'sandra', 'sandy', 'santiago', 'sara',
            'sarah', 'sasha', 'saul', 'sawyer', 'scarlett', 'scott',
            'selena', 'selma', 'serena', 'seth', 'shane', 'sharon',
            'shawn', 'shelby', 'sierra', 'silas', 'silvia', 'simone',
            'skylar', 'sofia', 'solomon', 'sonia', 'sophia', 'spencer',
            'stella', 'sterling', 'steven', 'stuart', 'sullivan', 'susan',
            'sylvia', 'tabitha', 'talia', 'tamara', 'tanner', 'tara',
            'tariq', 'tasha', 'taylor', 'teodoro', 'teresa', 'thatcher',
            'theo', 'thomas', 'tiffany', 'tobias', 'todd', 'tony',
            'tori', 'travis', 'trenton', 'trevor', 'tristan', 'troy',
            'tucker', 'tyler', 'ulysses', 'ursula', 'valentina', 'valerie',
            'vance', 'vanessa', 'vaughn', 'vera', 'verna', 'vernon',
            'veronica', 'victor', 'victoria', 'vincent', 'viola', 'violet',
            'virgil', 'virginia', 'vivian', 'wade', 'wallace', 'walter',
            'wanda', 'warren', 'wayne', 'wendy', 'wesley', 'whitney',
            'wilbur', 'willa', 'william', 'willow', 'wilson', 'winona',
            'winston', 'wyatt', 'xander', 'xavier', 'yara', 'yasmin',
            'yolanda', 'yuri', 'yvette', 'zachary', 'zane', 'zara',
            'zelda', 'zena', 'zion', 'zoe', 'zora',

            // ── More names ─────────────────────────────────────────────
            'abigail', 'adelina', 'agnes', 'aldo', 'alejandro', 'alessia',
            'alfonso', 'alfred', 'alicia', 'alina', 'alistair', 'allegra',
            'alvin', 'amanda', 'anabel', 'anderson', 'andres', 'angelica',
            'anita', 'annette', 'antonio', 'archie', 'arden', 'ariana',
            'arlo', 'armando', 'ashton', 'athena', 'atticus', 'august',
            'augustine', 'avery', 'banks', 'barbara', 'barnaby', 'barrett',
            'baxter', 'belinda', 'bellamy', 'benson', 'bernadette', 'bernard',
            'blaine', 'blair', 'bodhi', 'braxton', 'brent', 'brianna',
            'brigitte', 'brock', 'brody', 'callum', 'cameron', 'candace',
            'carlotta', 'caroline', 'cassandra', 'catalina', 'catherine', 'cecilia',
            'chandler', 'charlotte', 'christa', 'christian', 'christina', 'christopher',
            'claudia', 'clement', 'colleen', 'connie', 'constance', 'cordelia',
            'cornelius', 'cosmo', 'damian', 'damon', 'darcy', 'darius',
            'davina', 'deborah', 'delilah', 'della', 'demetri', 'denise',
            'dennis', 'destiny', 'dexter', 'dimitri', 'dolores', 'drake',
            'easton', 'edna', 'eleanor', 'elinor', 'elisabeth', 'elizabeth',
            'elodie', 'emerson', 'emilia', 'emmanuel', 'erica', 'erin',
            'estrella', 'eugene', 'fabio', 'felicity', 'fergus', 'fidel',
            'filippo', 'finnegan', 'francesca', 'frederic', 'genevieve', 'geoffrey',
            'gertrude', 'gilbert', 'giselle', 'gladys', 'gonzalo', 'gracie',
            'gregorio', 'gregory', 'griselda', 'hadley', 'hamilton', 'harding',
            'harmony', 'hayden', 'helena', 'hendrix', 'henrietta', 'herbert',
            'hillary', 'holden', 'horatio', 'ignatius', 'iker', 'ilona',
            'imogen', 'ines', 'ira', 'irwin', 'isadora', 'ismael',
            'jackson', 'jacqueline', 'jameson', 'janine', 'jarvis', 'jayden',
            'jefferson', 'jeremiah', 'jerome', 'jillian', 'joaquin', 'jocelyn',
            'jolene', 'josephine', 'josiah', 'jude', 'julius', 'katya',
            'keaton', 'kendra', 'killian', 'kingsley', 'kristina', 'kylie',
            'lamont', 'landry', 'langston', 'lawson', 'lazarus', 'leander',
            'lennox', 'leopold', 'leticia', 'levon', 'lillian', 'lincoln',
            'livia', 'lorenzo', 'lottie', 'lowell', 'lucius', 'ludwig',
            'maddox', 'maestro', 'marcella', 'margot', 'marisol', 'marlowe',
            'marshall', 'mathias', 'matthias', 'maureen', 'maximo', 'maxwell',
            'mckenna', 'mercedes', 'micah', 'millicent', 'minerva', 'monique',
            'montana', 'montgomery', 'natasha', 'nathaniel', 'nico', 'nigel',
            'nikita', 'nikolai', 'octavia', 'odessa', 'olympia', 'orville', 'osvaldo',
            'oswald', 'paloma', 'pandora', 'patience', 'penelope', 'percival',
            'persephone', 'peyton', 'philippa', 'phoebe', 'prescott', 'princeton',
            'priscilla', 'quincy', 'rachael', 'ramiro', 'randolph', 'raphael',
            'raul', 'reginald', 'reinhold', 'remington', 'renee', 'reynaldo',
            'rhiannon', 'ricardo', 'richmond', 'ridley', 'roberta', 'roderick',
            'rodney', 'rodrigo', 'roland', 'rosamund', 'rosemary', 'rosetta',
            'rowena', 'rudolph', 'rupert', 'sabine', 'salvatore', 'savannah',
            'sebastian', 'seraphina', 'sheldon', 'shepherd', 'sheridan', 'sherman',
            'sigrid', 'silvester', 'solange', 'soren', 'stanford', 'stanley',
            'stefanie', 'stirling', 'susannah', 'sutton', 'sybil', 'tatiana',
            'tempest', 'terrence', 'theodora', 'theodore', 'thornton', 'timothy',
            'truman', 'uriel', 'valentin', 'valerio', 'vasquez', 'velma',
            'vienna', 'vince', 'waldo', 'walker', 'watson', 'webster',
            'wellington', 'whitman', 'wilder', 'woodrow', 'yusuf', 'yvonne',
            'zachariah', 'zander', 'zavier',

            // ── Even more names ────────────────────────────────────────
            'adeline', 'adriana', 'ahmad', 'ainsley', 'alaric', 'albion',
            'aldric', 'alexis', 'althea', 'alton', 'alvaro', 'alyssa',
            'amari', 'ambrose', 'amira', 'angus', 'annalise', 'ansel',
            'arabella', 'aramis', 'augusto', 'avalon', 'aveline', 'aviva',
            'azalea', 'basilio', 'baylor', 'becky', 'benito', 'bertram',
            'bethel', 'beverly', 'birdie', 'blaire', 'bolivar', 'braden',
            'brennan', 'briar', 'broderick', 'brooklyn', 'calloway', 'camden',
            'carlyle', 'casper', 'celina', 'chandra', 'charlene', 'cisco',
            'clarice', 'clifton', 'coraline', 'cosima', 'crosby', 'dagny',
            'damaris', 'dashiell', 'davian', 'deidre', 'delphine', 'destin',
            'dimitrios', 'donovan', 'dorothea', 'edwina', 'efrain', 'elanor',
            'eliseo', 'elton', 'elvira', 'emilio', 'enoch', 'ephraim',
            'erasmus', 'estella', 'eudora', 'everest', 'fabienne', 'farrah',
            'fenella', 'findlay', 'finley', 'flavia', 'florian', 'gareth',
            'garrison', 'gemini', 'gianna', 'gillian', 'giovanna', 'giuliana',
            'greyson', 'guinevere', 'hamza', 'hartley', 'hassan', 'hendrix',
            'huxley', 'ibrahim', 'idris', 'indiana', 'ines', 'iolanda',
            'isidore', 'ivana', 'jabari', 'jacoby', 'jarrett', 'jelena',
            'jenifer', 'jericho', 'johanna', 'jolanda', 'kamila', 'kareem',
            'kasper', 'keanu', 'kiana', 'kingston', 'kirsten', 'kristoff',
            'lennon', 'leona', 'leopold', 'liliana', 'lorelei', 'lucille',
            'maddison', 'maisie', 'makayla', 'malachi', 'marcelo', 'matias',
            'maximus', 'melinda', 'meredith', 'mikaela', 'millard', 'missouri',
            'modesto', 'moreno', 'natalia', 'naveen', 'nevaeh', 'oakley',
            'octavio', 'odin', 'odette', 'olga', 'olympus', 'ondina',
            'padma', 'pascale', 'pearson', 'phoebe', 'pip', 'rafael',
            'ramsey', 'randal', 'rayna', 'renaldo', 'rhonda', 'rocio',
            'romina', 'rosalind', 'rowland', 'sahara', 'saoirse', 'seneca',
            'sterling', 'sunniva', 'sylvester', 'theron', 'timon', 'valeria',
            'vesper', 'vienna', 'vivienne', 'xena', 'xiomara', 'yasmine',
            'yesenia', 'zinnia', 'caspian', 'dashiel', 'elowen',
            'kenji', 'niamh', 'orla', 'thalia', 'tamsin', 'brinley',

            // ── More happy words & nature ──────────────────────────────
            'abundant', 'achieve', 'acoustic', 'action', 'aglow', 'aloha',
            'alpine', 'amuse', 'anthem', 'aqua', 'arctic', 'artful',
            'aura', 'awaken', 'beacon', 'blaze', 'blessing', 'bonfire',
            'bravo', 'canvas', 'cascade', 'celestial', 'center', 'chapel',
            'chorus', 'cinnamon', 'cobalt', 'compass', 'cosmic', 'courage',
            'cove', 'crimson', 'crown', 'cruise', 'daydream', 'dewdrop',
            'dusk', 'echo', 'encore', 'eternal', 'evening', 'feather',
            'festoon', 'flame', 'flicker', 'fountain', 'galaxy', 'garnet',
            'gaze', 'glacier', 'grove', 'halo', 'horizon', 'hymn',
            'indigo', 'kindle', 'lagoon', 'lantern', 'laurel', 'lullaby',
            'mesa', 'midnight', 'misty', 'mosaic', 'north', 'onyx',
            'orchid', 'panorama', 'pastel', 'pearl', 'pine', 'plaza',
            'plume', 'prairie', 'prism', 'quartz', 'reef', 'ridgeway',
            'rosewood', 'sable', 'safari', 'sahara', 'sandstone', 'satin',
            'sequoia', 'serenity', 'silk', 'snowfall', 'solstice', 'sonnet',
            'starlight', 'stardust', 'sunbeam', 'sundance', 'temple', 'terrace',
            'thistle', 'thunder', 'timber', 'tropic', 'twilight', 'umbrella',
            'valley', 'verdant', 'verve', 'villa', 'vista', 'woodland',
            'zenith', 'acacia', 'aspen', 'birch', 'bonsai', 'brook',
            'canyon', 'cliff', 'cloud', 'comet', 'copper', 'creek',
            'delta', 'dune', 'fjord', 'flint', 'granite', 'harbor',
            'haven', 'hollow', 'ivory', 'juniper', 'kelp', 'lake',
            'limestone', 'linden', 'magnolia', 'maple', 'marsh', 'meadow',
            'mesa', 'mineral', 'moraine', 'moss', 'mountain', 'nimbus',
            'oasis', 'palm', 'peak', 'pebble', 'prairie', 'quill',
            'rapids', 'ravine', 'ridge', 'ripple', 'savanna', 'shore',
            'slate', 'spruce', 'summit', 'tide', 'trail', 'tundra',
            'vale', 'volcano', 'waves', 'willow', 'breezy', 'caramel',
            'charming', 'colorful', 'content', 'coral', 'cosmic', 'crispy',
            'darling', 'dainty', 'dandy', 'delicate', 'devoted', 'dulcet',
            'earnest', 'elated', 'enchanted', 'exquisite', 'feisty', 'fern',
            'flora', 'folksy', 'gallant', 'genuine', 'glorious', 'gracious',
            'grateful', 'halcyon', 'handsome', 'heartfelt', 'heroic', 'homey',
            'hopeful', 'idyllic', 'inviting', 'iris', 'ivory', 'jaunty',
            'jubilant', 'kindness', 'kinetic', 'knightly', 'likable', 'limelight',
            'luminous', 'lustrous', 'lyrical', 'magnetic', 'mindful', 'mirthful',
            'moonlit', 'muse', 'mystical', 'natural', 'nimble', 'notable',
            'optimal', 'opulent', 'pacific', 'pageant', 'panda', 'pastoral',
            'pearly', 'perky', 'plentiful', 'poetic', 'polished', 'pristine',
            'prodigy', 'profound', 'quaint', 'queenly', 'radiance', 'regal',
            'reliant', 'resolute', 'restful', 'robust', 'romantic', 'rustic',
            'sanguine', 'seaside', 'sheltered', 'silken', 'skyline', 'snowflake',
            'spirited', 'splendid', 'sprightly', 'steadfast', 'stonework', 'sunlit',
            'surreal', 'tactful', 'tempest', 'terrific', 'thrilling', 'tranquil',
            'treetop', 'upbeat', 'valiant', 'venerable', 'visionary', 'vivacious',
            'whimsy', 'windmill', 'winsome', 'wondrous', 'youthful', 'zealous',
        ]));

        return static::$cached;
    }
}
